ViridianCity_PokemonCenter_1F_Text_FeelFreeToUsePC::
    .string "Please feel free to use that PC in\n"
    .string "the corner.\p"
    .string "The receptionist told me so.\n"
    .string "It's so kind of her!$"

ViridianCity_PokemonCenter_1F_Text_PokeCenterInEveryTown::
    .string "There's a POKéMON CENTER in every\n"
    .string "town ahead.\p"
    .string "They charge no money, so don't\n"
    .string "be shy about healing POKéMON.$"

ViridianCity_PokemonCenter_1F_Text_PokeCentersHealMons::
    .string "POKéMON CENTERS heal your tired,\n"
    .string "hurt, or fainted POKéMON.\p"
    .string "They make all POKéMON completely\n"
    .string "healthy.$"

ViridianCity_PokemonCenter_1F_Text_SecondNurse::
    .string "Hi, what can I do for you?$"

ViridianCity_PokemonCenter_1F_Text_SecondNurse_SelectMon::
    .string "Which Pokémon's EVs should I reset?$"

ViridianCity_PokemonCenter_1F_Text_SecondNurse_ResetEVs::
    .string "I've reset your EVs.$"

ViridianCity_PokemonCenter_1F_Text_SecondNurse_ComebackAnytime::
	.string "Come back anytime.$"

ViridianCity_PokemonCenter_1F_Text_SecondNurse_NoEgg::
	.string "Sorry, I can't modify the stats\n"
	.string "of an EGG.$"

ViridianCity_PokemonCenter_1F_Text_SecondNurse_NotEnoughMoney::
    .string "My services require ¥1000,\n"
    .string "you do not have enough money.$"
