CeladonCity_DepartmentStore_1F_Text_WelcomeToDeptStore::
    .string "Hello!\n"
    .string "Welcome to Celadon Dept. Store.\p"
    .string "The board on the right describes\n"
    .string "the store layout.$"

CeladonCity_DepartmentStore_1F_Text_FloorDescriptions::
    .string "1f: Service Counter\p"
    .string "2f: Trainer's Market\p"
    .string "3f: TV Game Shop\p"
    .string "4f: Wise Man Gifts\p"
    .string "5f: Drugstore\p"
    .string "Rooftop Square: Vending Machines$"

CeladonCity_DepartmentStore_1F_Text_ServiceCounter::
    .string "1f: Service Counter$"

